name: Upload

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish webextension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Build
        working-directory: packages/chrome/
        run: |
          npn install
          npm run build
      - name: Zip
        working-directory: packages/chrome/dist
        run: zip -r dist.zip *
      - name: Upload & release
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: packages/chrome/dist/dist.zip
          extension-id: khpkpbbcccdmmclmpigdgddabeilkdpd
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          publish: false
